-- Set the database and schema context
USE SCHEMA SCHEMACHANGE_DEMO.PUBLIC;

CREATE OR REPLACE TABLE TRIPS

(

    TRIPDURATION varchar(50),STARTTIME varchar(50),STOPTIME varchar(50),START_STATION_ID varchar(50),START_STATION_NAME varchar(50),START_STATION_LATITUDE varchar(50),START_STATION_LONGITUDE varchar(50),END_STATION_ID varchar(50),END_STATION_NAME varchar(50),END_STATION_LATITUDE varchar(50),END_STATION_LONGITUDE varchar(50),BIKEID varchar(50),MEMBERSHIP_TYPE varchar(50),USERTYPE varchar(50),BIRTH_YEAR varchar(50),GENDER varchar(20)
    --  TRIPDURATION VARCHAR
    -- ,STARTTIME VARCHAR
    -- ,STOPTIME VARCHAR
    -- ,START_STATION_ID VARCHAR
    -- ,START_STATION_NAME STRING
    -- ,START_STATION_LATITUDE VARCHAR
    -- ,START_STATION_LONGITUDE VARCHAR
    -- ,END_STATION_ID VARCHAR
    -- ,END_STATION_NAME STRING
    -- ,END_STATION_LATITUDE VARCHAR
    -- ,END_STATION_LONGITUDE VARCHAR
    -- ,BIKEID VARCHAR
    -- ,MEMBERSHIP_TYPE VARCHAR
    -- ,USERTYPE STRING
    -- ,BIRTH_YEAR VARCHAR
    -- ,GENDER VARCHAR
);

CREATE OR REPLACE STAGE TRIPS_LOAD
    URL = 's3://csvload/SnowflakesDataLoad/SnowChange/TripsData2.csv' 
	CREDENTIALS = ( AWS_KEY_ID = 'AKIA35Q5OJTU4LAFZ6EN' AWS_SECRET_KEY = 'ZoUi3AZ7oXdTS9z/sHlhooh4zmojwE4FLhG+zAVz' ) 
	DIRECTORY = ( ENABLE = true );
